name: Auto Push to Hugging Face

on:
  push:
    branches:
      - main  # Change to your branch if not using main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install git-lfs
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install

    - name: Commit changes
      run: |
        git config --global user.email "karate7800@gmail.com"
        git config --global user.name "karate7800"
        git lfs track "*.bin"  # Track any binary files
        git add .
        git commit -m "Auto commit from GitHub Actions"

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git push https://karate7800:$HF_TOKEN@huggingface.co/karate7800/test_553.git

        
